framework:
#    default_locale: '%locale%'
    default_locale: 'en'
    translator:
#        где хранятся переводы
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'