app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sale:
    path: /sale
    defaults:  { _controller: AppBundle:Sale:index }

homepage:
    path: /
    defaults:  { _controller: AppBundle:Default:index }

security_login:
    path: /login
    defaults:  { _controller: AppBundle:Security:login }

security_logout:
    path: /logout
    defaults:  { _controller: AppBundle:Security:logout }

user_registration:
    path: /register
    defaults:  { _controller: AppBundle:Registration:register }

category_show:
    path: /category/{name}
    defaults:  { _controller: AppBundle:Category:show,name:""}

item_list:
    path: /item
    defaults:  { _controller: AppBundle:Item:index}

item_page:
    path: /item/{id}{sl}
    defaults:  { _controller: AppBundle:Item:show,sl:"",id:""}
    requirements:
        sl: '/?'
        id: '[1-9][0-9]*'

item_edit:
    path: /item/edit/{id}
    defaults:  { _controller: AppBundle:Item:edit,id:""}
    requirements:
        id: '[1-9][0-9]*'

item_add:
    path: /item/add
    defaults:  { _controller: AppBundle:Item:add}

test:
    path: /item/test
    defaults:  { _controller: AppBundle:Item:test}

item_cart:
    path: /item/cart
    defaults:  { _controller: AppBundle:Item:cart}

item_change:
    path: /item/change
    defaults:  { _controller: AppBundle:Item:change}
