# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    text_export:
        class: AppBundle\Service\TextExporter
        arguments: ["@logger","%export_dir%"]
#        arguments: ["%export_dir%"]
#   sonata service
    admin.category:
            class: AppBundle\Admin\CategoryAdmin
            arguments: [~, AppBundle\Entity\Category, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Category }
    admin.item:
                class: AppBundle\Admin\ItemAdmin
                arguments: [~, AppBundle\Entity\Item, ~]
                tags:
                    - { name: sonata.admin, manager_type: orm, label: Item }
    admin.user:
                class: AppBundle\Admin\UserAdmin
                arguments: [~, AppBundle\Entity\User, ~]
                tags:
                    - { name: sonata.admin, manager_type: orm, label: User }